parameters:
    app.jwt_public_key: '%kernel.project_dir%/config/jwt/public.pem'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $userServiceUrl: '%env(USER_SERVICE_URL)%'
            string $productServiceUrl: '%env(PRODUCT_SERVICE_URL)%'
            string $orderServiceUrl: '%env(ORDER_SERVICE_URL)%'
            string $internalApiKey: '%env(INTERNAL_API_KEY)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\JwtValidationServiceInterface: '@App\Service\JwtValidationService'
    App\Service\ProxyServiceInterface: '@App\Service\ProxyService'

    App\Service\JwtValidationService:
        arguments:
            $jwtPublicKey: '%app.jwt_public_key%'

    App\EventListener\JwtToHeaderListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 10 }
